IMChat/IMChat/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using chatNow.Common;
using IMChat.Common;
using IMChat.Models;
using MongoDB.Bson;

namespace IMChat.Controllers
{
    public class ManagerController : BaseController
    {
        //
        // GET: /Manager/

        //完善用户信息界面
        public ActionResult Info()
        {
            Users user = GetUserInfo();
            return View("Manage", user);
        }
        //添加用户详细资料
        public ActionResult AddInfo(Users user)
        {
            string uid = Request["UserId"];
            if (MongoDBHelper.UpdateUser(user, ObjectId.Parse(uid)))
                return Content("true");
            return Content("更新失败");
        }
        //上传头像
        public ActionResult UploadImageView()
        {
            Users user = GetUserInfo();
            return View("UploadImageView", user);
        }
        //图片上传
        public ActionResult UploadImage()
        {
            var file = Request.Files["Filedata"];
            string fileName = file.FileName;
            Users user = GetUserInfo();
            string path = "../HeadImage/" + GetUserInfo().UserId + "/";
            string absloute = Request.MapPath("../HeadImage/" + user.UserId + "/");
            if (file != null)
            {
                if (!Directory.Exists(absloute))
                    Directory.CreateDirectory(absloute);
                file.SaveAs(absloute + fileName);
                user.HeadImage = fileName;
                if (MongoDBHelper.UpdateUser(user, user.UserId))
                {
                    LogHelper.WriteLog("用户" + user.UserId + "成功上传头像" + fileName);
                    return Content(path + fileName);
                }
                else
                    return Content("上传失败");
            }
            return Content("没有要上传的文件");
        }
        //修改密码
        public ActionResult ChangePWDView()
        {
            Users user = GetUserInfo();
            return View("ChangePWD", user);
        }
        public ActionResult ChangePWD()
        {
            string oldpwd = Request["OldPwd"];
            string newpwd = Request["NewPwd"];
            string repeatpwd = Request["RepeatPwd"];
            if (newpwd != repeatpwd)
                return Content("两次新密码不一致");
            if (oldpwd == newpwd)
                return Content("新旧密码相同");
            Users user = MongoDBHelper.GetUserByID(Request["UserId"]);
            if (user.Hash != PwdSalt.EncodePassword(oldpwd, user.Salt))
                return Content("原密码错误");
            if (MongoDBHelper.ChangePwd(newpwd, Request["UserId"], user.Salt))
            {
                //清除登录凭证
                ClearCookie();
                LogHelper.WriteLog("用户" + user.UserId + "密码修改成功");
                return Content("修改成功");
            }
            else
                return Content("修改失败");
        }
        //删除用户档案
        public ActionResult SignOffView()
        {
            return View("SignOff");
        }
        [HttpPost]
        public ActionResult SignOff()
        {
            Users user = GetUserInfo();
            if (MongoDBHelper.RemoveUser(user))
                return Content("true");
            return Content("false");
        }
    }
}

IMChat/IMChat/Views/Manager/ChangePWD.cshtml
@model IMChat.Models.Users
@{
    ViewBag.Title = "修改密码";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <div class="left">
        @Html.Partial("_LeftMenu")
    </div>
    <div class="right">
        <section id="loginForm">
            @{
                using (Ajax.BeginForm("ChangePWD", "Manager", new AjaxOptions
            {
                HttpMethod = "Post",
                OnSuccess = "success",
                Confirm = "确定修改吗？"
            }))
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>修改密码</legend>
                    <ol>
                        <li>
                            <label>旧密码：</label>
                            <input type="password" name="OldPwd" value="" />
                        </li>
                        <li>
                            <label>新密码：</label>
                            <input type="password" name="NewPwd" value="" />
                        </li>
                        <li>
                            <label>重复新密码：</label>
                            <input type="password" name="RepeatPwd" value="" />
                        </li>
                    </ol>
                    <input type="submit" value="修改密码" />
                    <p>
                        @Html.HiddenFor(m => m.UserId)
                    </p>
                </fieldset>
                }
            }
        </section>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function success(data) {
            if (data == '修改成功') {
                alert(data);
                window.location.href = "../Chat/Default";
            } else {
                alert(data);
            }
        }
    </script>
    <link type="text/css" href="~/Scripts/css/Layout.css" rel="stylesheet" />
}


IMChat/IMChat/Views/Manager/Manage.cshtml
@model IMChat.Models.Users
@{
    ViewBag.Title = "Manage";
}

<h2>用户管理</h2>
<div>
    <div class="left">
        @Html.Partial("_LeftMenu")
    </div>
    @{
        List<SelectListItem> list = new List<SelectListItem>();
        SelectListItem mail = new SelectListItem();
        mail.Text = "男";
        mail.Value = "1";
        SelectListItem femail = new SelectListItem();
        femail.Text = "女";
        femail.Value = "0";
        list.Add(mail);
        list.Add(femail);
    }
    <div class="right">
        @using (Ajax.BeginForm("AddInfo", "Manager", new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "success",
        Confirm = "确定修改吗？"
    }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <fieldset>
                <legend>信息修改</legend>
                <ol class="list">
                    <li>
                        @Html.LabelFor(m => m.UserName)
                        @Html.TextBoxFor(m => m.UserName, new { ReadOnly = "readonly" })
                    </li>
                    <li>
                        @Html.LabelFor(m => m.NickName)
                        @Html.TextBoxFor(m => m.NickName)
                    </li>
                    <li>
                        @Html.LabelFor(m => m.SignName)
                        @Html.TextBoxFor(m => m.SignName)
                    </li>
                    <li>
                        @Html.LabelFor(m => m.Gender)
                        @Html.DropDownListFor(m => m.Gender, list, "请选择")
                    </li>
                    <li>
                        @Html.LabelFor(m => m.Mobile)
                        @Html.TextBoxFor(m => m.Mobile)
                    </li>
                    <li>
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email)
                    </li>
                </ol>
            </fieldset>
            <p>
                @Html.HiddenFor(m => m.UserId)
                @Html.HiddenFor(m => m.Salt)
                @Html.HiddenFor(m => m.Hash)
                @Html.HiddenFor(m => m.HeadImage)
                @Html.HiddenFor(m => m.ExtenderInfo)
                @Html.HiddenFor(m => m.Status)
            </p>
            <p>
                <input type="submit" value="修改" />
            </p>
        }
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function success(data) {
            if (data == 'true') {
                alert('更新成功');
                window.location.reload();
            } else
                alert(data);

        }
    </script>
    <link type="text/css" href="~/Scripts/css/Layout.css" rel="stylesheet" />
}

IMChat/IMChat/Views/Manager/SignOff.cshtml
@model IMChat.Models.Users
@{
    ViewBag.Title = "删除用户资料";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <div class="left">
        @Html.Partial("_LeftMenu")
    </div>
    <div class="right">
        <section id="loginForm">
            @{
                using (Ajax.BeginForm("SignOff", "Manager", new AjaxOptions
            {
                HttpMethod = "Post",
                OnSuccess = "success",
                Confirm = "确定要删除吗？"
            }))
                {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend>删除用户</legend>
                    <input type="submit" value="删除用户资料，不可恢复" />
                </fieldset>
                }
            }
        </section>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function success(data) {
            if (data == 'true') {
                alert('注销成功');
                window.location.href = '../Chat/Default';
            } else {
                alert('失败')
            }
        }
    </script>
    <link type="text/css" href="~/Scripts/css/Layout.css" rel="stylesheet" />
}


IMChat/IMChat/Views/Manager/UploadImageView.cshtml
@model IMChat.Models.Users
@{
    ViewBag.Title = "上传用户头像";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <div class="left">
        @Html.Partial("_LeftMenu")
    </div>
    <div class="right">
        <section id="loginForm">
            @{
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset style="width: 400px;">
                    <legend>上传头像</legend>
                    <div style="margin-bottom: 30px;">
                        <img src="#" alt="#" style="display: none;" id="uploadImg" width="100" height="100" />
                    </div>
                    <div>
                        <input type="file" name="fileUpload" id="fileUpload" multiple="multiple" />
                        <a href="javascript:void(0)" id="sureUpload">上传头像</a>|<a href="javascript:void(0)" id="cancelUpload">取消上传</a>
                    </div>
                </fieldset>
            }
        </section>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link type="text/css" href="~/Scripts/Uploadify/uploadify.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/Uploadify/jquery.uploadify.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#fileUpload").uploadify({
                'swf': '../Scripts/Uploadify/uploadify.swf',    //指定swf文件(带进度条)   
                'uploader': '../Manager/UploadImage',          //后台处理的页面               

                'buttonImage': '../Scripts/Uploadify/img_upload.png',
                'height': 20,        //显示的高度和宽度，默认 height 30；width 120
                'width': 90,         //显示的高度和宽度，默认 height 30；width 120

                'auto': false,                 //设置为true 选择文件后自动上传
                'multi': false,                //设置为true将允许多文件上传

                'buttonText': '上传头像',           //按钮显示的文字
                'buttonCursor': 'hand',     //鼠标弄上去小手状
                'formData': {},             //发送给后台的其他参数通过formData指定
                'progressData': 'speed',    //当上传的时候，显示的内容，有‘percentage’ or ‘speed’两个选项，即显示百分比或显示上传速度；
                'fileTypeDesc': '请选择图片',      //这个属性值必须设置fileTypeExts属性后才有效，用来设置选择文件对话框中的提示文本，如设置fileTypeDesc为“请选择rar doc pdf文件”
                'fileTypeExts': '*.jpg;*.jpeg',   //设置可以选择的文件的类型，格式如：‘*.*’ ’*.doc;*.pdf;*.rar’ 。
                'fileSizeLimit': '2MB',                   //上传文件的大小限制 ，如果为整数型则表示以KB为单位的大小，如果是字符串，则可以使用(B, KB, MB, or GB)为单位，比如’2MB’；如果设置为0则表示无限制
                'onUploadError': function (file, errorCode, errorMsg, errorString) {
                    alert('文件: ' + file.name + ' 上传处理失败，请修改后重新上传 ');
                },
                'onUploadSuccess': function (file, data, response) {
                    if (response == true) {
                        alert(data);
                        $("#uploadImg").attr("src", data);
                        $("#uploadImg").css("display", "block");
                    } else
                        alert("上传失败");
                },                            //上传执行完成后执行方法

                //'queueSizeLimit': 10,//当允许多文件上传时，设置选择文件的个数，默认值为999 
                //'folder': '/UploadFiles',   //上传的文件夹 其实就是一参数 后台仍然需要接收 完全可以不要这玩意

                'removeCompleted': true,	//是否自动将已完成任务从队列中删除，如果设置为false则会一直保留此任务显示。
                'removeTimeout': 1,    //如果设置了任务完成后自动从队列中移除，则可以规定从完成到被移除的时间间隔。
                //requeueErrors	false	如果设置为true，则单个任务上传失败后将返回错误，并重新加入任务队列上传。
                'successTimeout': 30,	//文件上传成功后服务端应返回成功标志，此项设置返回结果的超时时间
                //fileDataName ：设置一个名字，在服务器处理程序中根据该名字来取上传文件的数据。默认为Filedata 
                'method': 'post' // 提交方式Post 或Get 默认为Post 


                //'fileTypeDesc': 'Image Files', //在浏览窗口底部的文件类型下拉菜单中显示的文本        
                //'queueID': 'fileQueue',//上传文件页面中，你想要用来作为文件队列的元素的id, 默认为false  自动生成,  不带#
                //checkScript ：用来判断上传选择的文件在服务器是否存在的后台处理程序的相对路径
            })
            //上传事件
            $("#sureUpload").click(function () {
                $('#fileUpload').uploadify('upload')
            })
            //取消上传
            $("#cancelUpload").click(function () {
                $('#fileUpload').uploadify('cancel')
            })
        })
    </script>
    <link type="text/css" href="~/Scripts/css/Layout.css" rel="stylesheet" />
}

